# Application Name
spring.application.name=aadhaar-services

# Database Configuration (Updated)
spring.datasource.url=jdbc:postgresql://dpg-d464afv5r7bs73aug23g-a.singapore-postgres.render.com:5432/aadhaar_services_7k2i
spring.datasource.username=aadhaar_services_7k2i_user
spring.datasource.password=2NV64m38RaGQ8gHyDJZPprOhx7skOm5W
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (auto-create tables)
spring.jpa.hibernate.ddl-auto=update

# Set this to 'false' in production
spring.jpa.show-sql=false

# Server Port
server.port=${PORT:8082}

# Admin Secret
admin.secret-key=ADMIN_SECRET_123

# JWT Config
jwt.secret=ZGl0b1Nob2FyaGFqYXJiYXRpU2hvdGFwYXJpYahkhdfkahkdhfahjkdhfkahhfdhdhfkahdf
jwt.expiration=3600000

# File upload settings
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB